apiVersion: apps/v1
kind: Deployment
metadata:
  name: architect-playbook-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: architect-api
  template:
    metadata:
      labels:
        app: architect-api
    spec:
      containers:
        - name: api
          image: architect-playbook-api:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: architect-api
spec:
  selector:
    app: architect-api
  ports:
    - port: 80
      targetPort: 8080
